---
version: "2"

run:
  go: 1.24.7
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errortype
  settings:
    custom:
      errortype:
        type: module
        description: "errortype helps prevent subtle bugs in error handling."
        original-url: "https://fillmore-labs.com/errortype"
        settings:
          overrides:
            pointer:
              - test/a.PointerOverride
            value:
              - test/a.ValueOverride
            suppress:
              - test/a.SuppressOverride
          style-check: true
          deep-is-check: false
          check-is: true
          unchecked-assert: false
