---
template: matryer
template-data:
  stub-impl: false

filename: mocks_test.go
pkgname: "{{.SrcPackageName}}_test"
structname: "moq{{.InterfaceName}}"

packages:
  fillmore-labs.com/errortype/internal/analyze/usage:
    interfaces:
      Reporter:
        config:
