// Code generated by "stringer -type ErrorFact -linecomment"; DO NOT EDIT.

package facts

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UndecidedType-0]
	_ = x[PointerType-1]
	_ = x[ValueType-2]
	_ = x[SuppressType-3]
	_ = x[ExpectedMask-3]
}

const _ErrorFact_name = "UndecidedPointerValueSuppress"

var _ErrorFact_index = [...]uint8{0, 9, 16, 21, 29}

func (i ErrorFact) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ErrorFact_index)-1 {
		return "ErrorFact(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorFact_name[_ErrorFact_index[idx]:_ErrorFact_index[idx+1]]
}
