// Code generated by "stringer -output=errortype/internal/detect/heuristicpass_string.go -type=HeuristicPass -linecomment errortype/internal/detect/options.go"; DO NOT EDIT.

package detect

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HeuristicUsage-1]
	_ = x[HeuristicReceivers-2]
	_ = x[HeuristicOff-0]
}

const _HeuristicPass_name = "offusagereceivers"

var _HeuristicPass_index = [...]uint8{0, 3, 8, 17}

func (i HeuristicPass) String() string {
	if i >= HeuristicPass(len(_HeuristicPass_index)-1) {
		return "HeuristicPass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HeuristicPass_name[_HeuristicPass_index[i]:_HeuristicPass_index[i+1]]
}
