// Code generated by bitmask; DO NOT EDIT.

package detect

import (
	"fmt"

	"fillmore-labs.com/errortype/internal/bitmask"
)

// Set adjusts the bitmask by enabling or disabling the specified mask.
func (h *Heuristics) Set(mask Heuristics, value bool) {
	if value {
		*h |= mask
	} else {
		*h &^= mask
	}
}

// Has reports whether every bit in mask is set on the receiver. With a multi-bit mask
// it is a strict containment check; calling Has(0) always returns true.
func (h Heuristics) Has(mask Heuristics) bool {
	return h&mask == mask
}

// String returns the textual representation of Heuristics.
func (h Heuristics) String() string {
	switch h {
	case HeuristicAll:
		return "all"
	case HeuristicOff:
		return "off"
	}

	txt, err := bitmask.FormatText(uint64(h), _HeuristicsNames[:]) // #nosec G115 -- validated during generation.
	if err != nil {
		return "Heuristics: " + err.Error()
	}

	return txt
}

// MarshalText implements [encoding.TextMarshaler].
func (h Heuristics) MarshalText() ([]byte, error) {
	return h.AppendText(nil)
}

// AppendText implements [encoding.TextAppender].
func (h Heuristics) AppendText(buf []byte) ([]byte, error) {
	switch h {
	case HeuristicAll:
		return append(buf, "all"...), nil
	case HeuristicOff:
		return append(buf, "off"...), nil
	}

	return bitmask.AppendText(buf, uint64(h), _HeuristicsNames[:]) // #nosec G115 -- validated during generation.
}

// UnmarshalText implements [encoding.TextUnmarshaler].
// It parses a comma- or whitespace-separated list of names.
func (h *Heuristics) UnmarshalText(text []byte) error {
	val, err := bitmask.UnmarshalText(text, _HeuristicsParseName)
	if err != nil {
		return fmt.Errorf("Heuristics: %w", err)
	}

	*h = Heuristics(val) // #nosec G115 -- validated during generation.

	return nil
}

var _HeuristicsNames = [...]string{
	"var",
	"usage",
	"receivers",
}

// _HeuristicsParseName resolves "name" to its bit value, reporting
// whether it was recognized.
func _HeuristicsParseName(name string) (uint64, bool) {
	switch name {
	case "all":
		return uint64(HeuristicAll), true
	case "off":
		return uint64(HeuristicOff), true
	case "var":
		return uint64(HeuristicVar), true
	case "usage":
		return uint64(HeuristicUsage), true
	case "receivers":
		return uint64(HeuristicReceivers), true
	default:
		return 0, false
	}
}
