// Code generated by "stringer -type Heuristic -linecomment"; DO NOT EDIT.

package detect

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HeuristicOff-0]
	_ = x[HeuristicUsage-1]
	_ = x[HeuristicReceivers-2]
}

const _Heuristic_name = "offusagereceivers"

var _Heuristic_index = [...]uint8{0, 3, 8, 17}

func (i Heuristic) String() string {
	if i >= Heuristic(len(_Heuristic_index)-1) {
		return "Heuristic(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Heuristic_name[_Heuristic_index[i]:_Heuristic_index[i+1]]
}
