// Code generated by "stringer -type Heuristic -linecomment"; DO NOT EDIT.

package detect

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HeuristicOff-0]
	_ = x[HeuristicVar-1]
	_ = x[HeuristicUsage-2]
	_ = x[HeuristicReceivers-3]
}

const _Heuristic_name = "offvarusagereceivers"

var _Heuristic_index = [...]uint8{0, 3, 6, 11, 20}

func (i Heuristic) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Heuristic_index)-1 {
		return "Heuristic(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Heuristic_name[_Heuristic_index[idx]:_Heuristic_index[idx+1]]
}
