// Code generated by "stringer -type Override -linecomment"; DO NOT EDIT.

package detect

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OverridePointer-1]
	_ = x[OverrideValue-2]
	_ = x[OverrideSuppress-3]
}

const _Override_name = "pointervaluesuppress"

var _Override_index = [...]uint8{0, 7, 12, 20}

func (i Override) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Override_index)-1 {
		return "Override(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Override_name[_Override_index[idx]:_Override_index[idx+1]]
}
