// Code generated by bitmask; DO NOT EDIT.

package analyze

import (
	"fmt"
	"strconv"

	"fillmore-labs.com/errortype/internal/bitmask"
)

// Set adjusts the bitmask by enabling or disabling the specified mask.
func (o *Options) Set(mask Options, value bool) {
	if value {
		*o |= mask
	} else {
		*o &^= mask
	}
}

// Has reports whether every bit in mask is set on the receiver. With a multi-bit mask
// it is a strict containment check; calling Has(0) always returns true.
func (o Options) Has(mask Options) bool {
	return o&mask == mask
}

// String returns the textual representation of Options.
func (o Options) String() string {
	txt, err := bitmask.FormatText(uint64(o), _OptionsNames[:]) // #nosec G115 -- validated during generation.
	if err != nil {
		return "Options: " + err.Error()
	}

	return txt
}

// MarshalText implements [encoding.TextMarshaler].
func (o Options) MarshalText() ([]byte, error) {
	return o.AppendText(nil)
}

// AppendText implements [encoding.TextAppender].
func (o Options) AppendText(buf []byte) ([]byte, error) {
	return bitmask.AppendText(buf, uint64(o), _OptionsNames[:]) // #nosec G115 -- validated during generation.
}

// UnmarshalText implements [encoding.TextUnmarshaler].
// It parses a comma- or whitespace-separated list of names.
func (o *Options) UnmarshalText(text []byte) error {
	val, err := bitmask.UnmarshalText(text, _OptionsParseName)
	if err != nil {
		return fmt.Errorf("Options: %w", err)
	}

	*o = Options(val) // #nosec G115 -- validated during generation.

	return nil
}

var _OptionsNames = [...]string{
	"check-is",
	"check-unused",
	"deep-is-check",
	"style-check",
	"unchecked-assert",
	"prefix-filter",
	"non-comparable",
	"naming",
	"legacy",
	"generated",
}

// _OptionsParseName resolves "name" to its bit value, reporting
// whether it was recognized.
func _OptionsParseName(name string) (uint64, bool) {
	switch name {
	case "check-is":
		return uint64(OptionCheckIs), true
	case "check-unused":
		return uint64(OptionCheckUnused), true
	case "deep-is-check":
		return uint64(OptionDeepIsCheck), true
	case "style-check":
		return uint64(OptionStyleCheck), true
	case "unchecked-assert":
		return uint64(OptionUncheckedAssert), true
	case "prefix-filter":
		return uint64(OptionPrefixFilter), true
	case "non-comparable":
		return uint64(OptionNotComparable), true
	case "naming":
		return uint64(OptionNaming), true
	case "legacy":
		return uint64(OptionLegacy), true
	case "generated":
		return uint64(OptionGenerated), true
	default:
		return 0, false
	}
}

// BoolFlag returns a boolean [flag.Value] for o.
//
// Use it with
//
//	var o Options
//	flag.Var(o.BoolFlag(OptionCheckIs), "name", "usage")
func (o *Options) BoolFlag(mask Options) OptionsBoolFlag {
	return OptionsBoolFlag{value: o, mask: mask}
}

// OptionsBoolFlag implements [flag.Value] to bind a Options configuration to a specific flag for command-line parsing.
type OptionsBoolFlag struct {
	value *Options
	mask  Options
}

// String implements [flag.Value].
func (v OptionsBoolFlag) String() string {
	return strconv.FormatBool(v.value != nil && v.value.Has(v.mask))
}

// Set implements [flag.Value].
func (v OptionsBoolFlag) Set(s string) error {
	value, err := strconv.ParseBool(s)
	if err != nil {
		return err
	}

	v.value.Set(v.mask, value)

	return nil
}

// IsBoolFlag makes `-name` equivalent to `-name=true`.
func (OptionsBoolFlag) IsBoolFlag() bool { return true }
