// Code generated by bitmask; DO NOT EDIT.

package properties

import (
	"fmt"

	"fillmore-labs.com/errortype/internal/bitmask"
)

// Set adjusts the bitmask by enabling or disabling the specified mask.
func (e *ErrorProperty) Set(mask ErrorProperty, value bool) {
	if value {
		*e |= mask
	} else {
		*e &^= mask
	}
}

// Has reports whether every bit in mask is set on the receiver. With a multi-bit mask
// it is a strict containment check; calling Has(0) always returns true.
func (e ErrorProperty) Has(mask ErrorProperty) bool {
	return e&mask == mask
}

// String returns the textual representation of ErrorProperty.
func (e ErrorProperty) String() string {
	txt, err := bitmask.FormatText(uint64(e), _ErrorPropertyNames[:]) // #nosec G115 -- validated during generation.
	if err != nil {
		return "ErrorProperty: " + err.Error()
	}

	return txt
}

// MarshalText implements [encoding.TextMarshaler].
func (e ErrorProperty) MarshalText() ([]byte, error) {
	return e.AppendText(nil)
}

// AppendText implements [encoding.TextAppender].
func (e ErrorProperty) AppendText(buf []byte) ([]byte, error) {
	return bitmask.AppendText(buf, uint64(e), _ErrorPropertyNames[:]) // #nosec G115 -- validated during generation.
}

// UnmarshalText implements [encoding.TextUnmarshaler].
// It parses a comma- or whitespace-separated list of names.
func (e *ErrorProperty) UnmarshalText(text []byte) error {
	val, err := bitmask.UnmarshalText(text, _ErrorPropertyParseName)
	if err != nil {
		return fmt.Errorf("ErrorProperty: %w", err)
	}

	*e = ErrorProperty(val) // #nosec G115 -- validated during generation.

	return nil
}

var _ErrorPropertyNames = [...]string{
	"SuppressOverride",
	"PointerOverride",
	"ValueOverride",
	"PointerReceiver",
	"PointerMethod",
	"Embedded",
	"EmbeddedMethod",
	"PointerAlias",
	"ValueAlias",
	"PointerVar",
	"ValueVar",
	"PointerReturn",
	"ValueReturn",
	"PointerAssert",
	"ValueAssert",
	"PointerTarget",
	"ValueTarget",
	"PointerLiteral",
	"ValueLiteral",
	"PointerCast",
	"ValueCast",
	"PointerReceivers",
	"ValueReceivers",
	"PointerDef",
	"NonStruct",
	"ZeroSized",
}

// _ErrorPropertyParseName resolves "name" to its bit value, reporting
// whether it was recognized.
func _ErrorPropertyParseName(name string) (uint64, bool) {
	switch name {
	case "SuppressOverride":
		return uint64(SuppressOverride), true
	case "PointerOverride":
		return uint64(PointerOverride), true
	case "ValueOverride":
		return uint64(ValueOverride), true
	case "PointerReceiver":
		return uint64(PointerReceiver), true
	case "PointerMethod":
		return uint64(PointerMethod), true
	case "Embedded":
		return uint64(Embedded), true
	case "EmbeddedMethod":
		return uint64(EmbeddedMethod), true
	case "PointerAlias":
		return uint64(PointerAlias), true
	case "ValueAlias":
		return uint64(ValueAlias), true
	case "PointerVar":
		return uint64(PointerVar), true
	case "ValueVar":
		return uint64(ValueVar), true
	case "PointerReturn":
		return uint64(PointerReturn), true
	case "ValueReturn":
		return uint64(ValueReturn), true
	case "PointerAssert":
		return uint64(PointerAssert), true
	case "ValueAssert":
		return uint64(ValueAssert), true
	case "PointerTarget":
		return uint64(PointerTarget), true
	case "ValueTarget":
		return uint64(ValueTarget), true
	case "PointerLiteral":
		return uint64(PointerLiteral), true
	case "ValueLiteral":
		return uint64(ValueLiteral), true
	case "PointerCast":
		return uint64(PointerCast), true
	case "ValueCast":
		return uint64(ValueCast), true
	case "PointerReceivers":
		return uint64(PointerReceivers), true
	case "ValueReceivers":
		return uint64(ValueReceivers), true
	case "PointerDef":
		return uint64(PointerDef), true
	case "NonStruct":
		return uint64(NonStruct), true
	case "ZeroSized":
		return uint64(ZeroSized), true
	default:
		return 0, false
	}
}
