---
recommended: true
non-comparable: true
naming: true
legacy: true
style-check: true
deep-is-check: false
check-is: true
unchecked-assert: false
check-unused: false
prefix-filter: true
overrides:
  pointer:
    - your.pkg/a.PointerOverrideError
  value:
    - your.pkg/a.ValueOverrideError
  suppress:
    - your.pkg/a.SuppressOverrideError
wrappers:
  is:
    - your.pkg/a.Is
  as:
    - your.pkg/a.As
  astype:
    - your.pkg/a.AsType
