---
overrides:
  pointer:
    - test/a.PointerOverride
  value:
    - test/a.ValueOverride
  suppress:
    - test/a.SuppressOverride
style-check: true
deep-is-check: false
check-is: true
unchecked-assert: false
check-unused: false
