---
naming: true
style-check: true
deep-is-check: false
check-is: true
unchecked-assert: false
check-unused: false
overrides:
  pointer:
    - test/a.PointerOverride
  value:
    - test/a.ValueOverride
  suppress:
    - test/a.SuppressOverride
wrappers:
  is:
    - test/a.Is
  as:
    - test/a.As
  astype:
    - test/a.AsType
