---
when:
  - event: push
    branch: [main, dev]

matrix:
  GO_VERSION:
    - '1.26.4'
    - '1.25.11'

steps:
  - name: test
    image: golang:${GO_VERSION}
    environment:
      GOTOOLCHAIN: local
    commands:
      - go mod download && (cd ./analyzer/testdata && go mod download)
      - echo "🔨 Testing on $(go version):"
      - go test ./...
