// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package usage_test

import (
	"go/types"
	"sync"

	"fillmore-labs.com/errortype/internal/analyze/usage"
)

// Ensure that moqReporter does implement usage.Reporter.
// If this is not the case, regenerate this file with mockery.
var _ usage.Reporter = &moqReporter{}

// moqReporter is a mock implementation of usage.Reporter.
//
//	func TestSomethingThatUsesReporter(t *testing.T) {
//
//		// make and configure a mocked usage.Reporter
//		mockedReporter := &moqReporter{
//			ShouldBePointerFunc: func(tn *types.TypeName)  {
//				panic("mock out the ShouldBePointer method")
//			},
//			ShouldBeValueFunc: func(tn *types.TypeName)  {
//				panic("mock out the ShouldBeValue method")
//			},
//			UndeterminedUsageFunc: func(tn *types.TypeName, ptr bool)  {
//				panic("mock out the UndeterminedUsage method")
//			},
//		}
//
//		// use mockedReporter in code that requires usage.Reporter
//		// and then make assertions.
//
//	}
type moqReporter struct {
	// ShouldBePointerFunc mocks the ShouldBePointer method.
	ShouldBePointerFunc func(tn *types.TypeName)

	// ShouldBeValueFunc mocks the ShouldBeValue method.
	ShouldBeValueFunc func(tn *types.TypeName)

	// UndeterminedUsageFunc mocks the UndeterminedUsage method.
	UndeterminedUsageFunc func(tn *types.TypeName, ptr bool)

	// calls tracks calls to the methods.
	calls struct {
		// ShouldBePointer holds details about calls to the ShouldBePointer method.
		ShouldBePointer []struct {
			// Tn is the tn argument value.
			Tn *types.TypeName
		}
		// ShouldBeValue holds details about calls to the ShouldBeValue method.
		ShouldBeValue []struct {
			// Tn is the tn argument value.
			Tn *types.TypeName
		}
		// UndeterminedUsage holds details about calls to the UndeterminedUsage method.
		UndeterminedUsage []struct {
			// Tn is the tn argument value.
			Tn *types.TypeName
			// Ptr is the ptr argument value.
			Ptr bool
		}
	}
	lockShouldBePointer   sync.RWMutex
	lockShouldBeValue     sync.RWMutex
	lockUndeterminedUsage sync.RWMutex
}

// ShouldBePointer calls ShouldBePointerFunc.
func (mock *moqReporter) ShouldBePointer(tn *types.TypeName) {
	if mock.ShouldBePointerFunc == nil {
		panic("moqReporter.ShouldBePointerFunc: method is nil but Reporter.ShouldBePointer was just called")
	}
	callInfo := struct {
		Tn *types.TypeName
	}{
		Tn: tn,
	}
	mock.lockShouldBePointer.Lock()
	mock.calls.ShouldBePointer = append(mock.calls.ShouldBePointer, callInfo)
	mock.lockShouldBePointer.Unlock()
	mock.ShouldBePointerFunc(tn)
}

// ShouldBePointerCalls gets all the calls that were made to ShouldBePointer.
// Check the length with:
//
//	len(mockedReporter.ShouldBePointerCalls())
func (mock *moqReporter) ShouldBePointerCalls() []struct {
	Tn *types.TypeName
} {
	var calls []struct {
		Tn *types.TypeName
	}
	mock.lockShouldBePointer.RLock()
	calls = mock.calls.ShouldBePointer
	mock.lockShouldBePointer.RUnlock()
	return calls
}

// ShouldBeValue calls ShouldBeValueFunc.
func (mock *moqReporter) ShouldBeValue(tn *types.TypeName) {
	if mock.ShouldBeValueFunc == nil {
		panic("moqReporter.ShouldBeValueFunc: method is nil but Reporter.ShouldBeValue was just called")
	}
	callInfo := struct {
		Tn *types.TypeName
	}{
		Tn: tn,
	}
	mock.lockShouldBeValue.Lock()
	mock.calls.ShouldBeValue = append(mock.calls.ShouldBeValue, callInfo)
	mock.lockShouldBeValue.Unlock()
	mock.ShouldBeValueFunc(tn)
}

// ShouldBeValueCalls gets all the calls that were made to ShouldBeValue.
// Check the length with:
//
//	len(mockedReporter.ShouldBeValueCalls())
func (mock *moqReporter) ShouldBeValueCalls() []struct {
	Tn *types.TypeName
} {
	var calls []struct {
		Tn *types.TypeName
	}
	mock.lockShouldBeValue.RLock()
	calls = mock.calls.ShouldBeValue
	mock.lockShouldBeValue.RUnlock()
	return calls
}

// UndeterminedUsage calls UndeterminedUsageFunc.
func (mock *moqReporter) UndeterminedUsage(tn *types.TypeName, ptr bool) {
	if mock.UndeterminedUsageFunc == nil {
		panic("moqReporter.UndeterminedUsageFunc: method is nil but Reporter.UndeterminedUsage was just called")
	}
	callInfo := struct {
		Tn  *types.TypeName
		Ptr bool
	}{
		Tn:  tn,
		Ptr: ptr,
	}
	mock.lockUndeterminedUsage.Lock()
	mock.calls.UndeterminedUsage = append(mock.calls.UndeterminedUsage, callInfo)
	mock.lockUndeterminedUsage.Unlock()
	mock.UndeterminedUsageFunc(tn, ptr)
}

// UndeterminedUsageCalls gets all the calls that were made to UndeterminedUsage.
// Check the length with:
//
//	len(mockedReporter.UndeterminedUsageCalls())
func (mock *moqReporter) UndeterminedUsageCalls() []struct {
	Tn  *types.TypeName
	Ptr bool
} {
	var calls []struct {
		Tn  *types.TypeName
		Ptr bool
	}
	mock.lockUndeterminedUsage.RLock()
	calls = mock.calls.UndeterminedUsage
	mock.lockUndeterminedUsage.RUnlock()
	return calls
}
