// Code generated by bitmask; DO NOT EDIT.

package usage

import (
	"fmt"

	"fillmore-labs.com/errortype/internal/bitmask"
)

// Set adjusts the bitmask by enabling or disabling the specified mask.
func (u *Usage) Set(mask Usage, value bool) {
	if value {
		*u |= mask
	} else {
		*u &^= mask
	}
}

// Has reports whether every bit in mask is set on the receiver. With a multi-bit mask
// it is a strict containment check; calling Has(0) always returns true.
func (u Usage) Has(mask Usage) bool {
	return u&mask == mask
}

// String returns the textual representation of Usage.
func (u Usage) String() string {
	txt, err := bitmask.FormatText(uint64(u), _UsageNames[:]) // #nosec G115 -- validated during generation.
	if err != nil {
		return "Usage: " + err.Error()
	}

	return txt
}

// MarshalText implements [encoding.TextMarshaler].
func (u Usage) MarshalText() ([]byte, error) {
	return u.AppendText(nil)
}

// AppendText implements [encoding.TextAppender].
func (u Usage) AppendText(buf []byte) ([]byte, error) {
	return bitmask.AppendText(buf, uint64(u), _UsageNames[:]) // #nosec G115 -- validated during generation.
}

// UnmarshalText implements [encoding.TextUnmarshaler].
// It parses a comma- or whitespace-separated list of names.
func (u *Usage) UnmarshalText(text []byte) error {
	val, err := bitmask.UnmarshalText(text, _UsageParseName)
	if err != nil {
		return fmt.Errorf("Usage: %w", err)
	}

	*u = Usage(val) // #nosec G115 -- validated during generation.

	return nil
}

var _UsageNames = [...]string{
	"PointerExpected",
	"ValueExpected",
	"PointerObserved",
	"ValueObserved",
}

// _UsageParseName resolves "name" to its bit value, reporting
// whether it was recognized.
func _UsageParseName(name string) (uint64, bool) {
	switch name {
	case "PointerExpected":
		return uint64(PointerExpected), true
	case "ValueExpected":
		return uint64(ValueExpected), true
	case "PointerObserved":
		return uint64(PointerObserved), true
	case "ValueObserved":
		return uint64(ValueObserved), true
	default:
		return 0, false
	}
}
