// Code generated by "stringer -type ErrorType -linecomment"; DO NOT EDIT.

package errortypes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Undecided-0]
	_ = x[PointerType-1]
	_ = x[ValueType-2]
	_ = x[SuppressType-3]
}

const _ErrorType_name = "UndecidedPointerValueSuppress"

var _ErrorType_index = [...]uint8{0, 9, 16, 21, 29}

func (i ErrorType) String() string {
	if i >= ErrorType(len(_ErrorType_index)-1) {
		return "ErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorType_name[_ErrorType_index[i]:_ErrorType_index[i+1]]
}
