---
name: Test
"on":
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test on Go ${{ matrix.go }}
    permissions:
      checks: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        go: ["1.25", "1.24"]
        include:
          - go: "1.25"
            go-version: "1.25.0"
            update-meta: true
          - go: "1.24"
            go-version: "1.24.6"
    env:
      GOTOOLCHAIN: local
    steps:
      - name: ✔ Check out
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      - name: 🐹 Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5.5.0
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: "**/go.sum"
      - name: 🧸 golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9  # v8.0.0
        with:
          version: v2.4.0
      - name: 🔨 Test
        run: |
          (cd ./internal/analyze/testdata && go mod download)
          go test -coverprofile=cover.out ./...
        env:
          GOEXPERIMENT: aliastypeparams
      - name: 🧑🏻‍💻 codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24  # v5.4.3
        if: ${{ matrix.update-meta }}
        with:
          files: ./cover.out
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: 🛜 Dependencies
        uses: actions/go-dependency-submission@f35d5c9af13ce9cc32f7930b171e315e878f6921  # v2.0.3
        if: ${{ matrix.update-meta }}
        with:
          go-mod-path: go.mod
          go-build-target: .
